#!/bin/bash
# capturesh
# Capture any input typed into bash's 'readline' - done via
# Brendan Gregg's superb perf-tools[-unstable] 'uprobe-perf'.
name=$(basename $0)
LOG=~/log.capturesh
LK=~/.${name}.lck
LIN="------------------------------------------------------------------------"

trap 'rm -f ${LK}' INT QUIT

[ -f ${LK} ] && {
 echo "${name}: lock file present, aborting.."
 exit 1
}
touch ${LK}

echo "${LIN}
$(date)
$(id)
${LIN}" |tee -a ${LOG}
sudo uprobe-perf 'r:bash:readline +0($retval):string' |tee -a ${LOG}
# NOTE
#  doesn't work when an alias is used?? It Does.
rm -f ${LK}
exit 0
