#!/bin/bash
# coccichk
# 
# Quick Description:
# Run the Linux kernel's cocinelle semantic patch checkers on a given
# source file(s) or folder. Realistically, a wrapper over spatch.
#
# Last Updated :
# Created      : 23Aug2017
# 
# Author:
# Kaiwan N Billimoria
# kaiwan -at- kaiwantech -dot- com
# kaiwanTECH
# 
# License:
# MIT License.
name=$(basename $0)

########### Globals follow #########################
# Style: gNameOfGlobalVar

gInitMsg=\
"@@@ ${name}: WARNING! Don't blindly act on coccinelle's output @@@
@@@ False positives can and do occur. Verify your code.         @@@
@@@ (Also, it works only on C source/header files, nothing else)@@@
"
# kernel source tree location: !UPDATE for your box!
gKSRC_LOC=~/big/kernels/linux-4.4.21/ #~/git-kernel-latest/
gVERBOSE=0

########### Functions follow #######################

runcocci()
{
[ $# -ne 1 ] && return
local cocci
local SP_BASEOPTS="-D report --very-quiet --include-headers"
local msg

# If first parameter is a directory, then work on all source files within it
if [ -d $1 ] ; then
  SP_OPTS="${SP_BASEOPTS} --dir $1"
  msg="#Folder:${1}"
else
  msg="#FILE:${1}"
fi

echo "${msg}"
# Loop over all cocci sp's (semantic patches)
for cocci in $(find ${gKSRC_LOC}/scripts/coccinelle/ -name "*.cocci")
do
 [ ${gVERBOSE} -eq 1 ] && echo "*--$(basename ${cocci})--*"
 spatch ${SP_BASEOPTS} --sp-file ${cocci} ${1}
done
} # end runcocci()


##### 'main' : execution starts here #####

parent=$(ps -o comm= $PPID)
which spatch >/dev/null || {
  echo "${name}: coccinelle (spatch) not installed?"
  exit 1
}
[ ! -d ${gKSRC_LOC} ] && {
  echo "${name}: kernel source tree location \"${KSRC_LOC}\" invalid?"
  [ "${parent}" = "bash" ] && exit 1 || return 1
}
[ $# -lt 1 ] && {
  echo "Usage: ${name} <source-pathname(s)> file1 [file2] [file3] ...
  -OR-
${name} source-folder"
  [ "${parent}" = "bash" ] && exit 1 || return 1
}

echo "${gInitMsg}"

# TODO
# Handle ^C ^\ properly; kill all spatch processes

# If a folder passed as $1
if [ -d $1 ] ; then
  runcocci $1
  [ "${parent}" = "bash" ] && exit 0 || return 0
fi

# If one or more files are passed, or a wildcard..
for fname in "$@"
do
  file ${fname} |egrep -q "C source" || {
    echo "${name}: skipping ${fname} .."
	continue
  }
    # RELOOK: will spatch play nicely with C++ ?? As of now, we don't process it

  [ ! -f ${fname} -o ! -r ${fname} ] && {
    echo "${name}: source file \"${fname}\" does not exist or unreadable?"
	continue
  }
  runcocci ${fname}
done
[ "${parent}" = "bash" ] && exit 0 || return 0
