#!/bin/bash
# silly kernel module dev helper wrapper script

unset ARCH
unset CROSS_COMPILE

name=$(basename $0)
#[ `id -u` -ne 0 ] && {
# echo "$name: Need to be root!"
# exit 1
#}

SEP="-----------------------------------------------------------------------"
if [ $# -ne 1 ]; then
	echo "Usage: $name name-of-kernel-module-file (without the .c)"
#-------------- r u n c m d -------------------------------------------
# Display and run the provided command.
# Parameter 1 : the command to run
runcmd()
{
local SEP="------------------------------"
[ $# -eq 0 ] && return
echo "${SEP}
$@
${SEP}"
eval "$@"
[ $? -ne 0 ] && echo " ^--[FAILED]"
}

### "main" here
	exit 1
fi

if [[ "${1}" = *"."* ]]; then
	echo "Usage: $name name-of-kernel-module-file ONLY (do NOT put any extension)."
	exit 1
fi

echo $SEP
echo "Version info:"
# TODO - take into a/c diff Linux distros
#cat /etc/fedora-release
#cat /etc/issue
uname -r

runcmd "sudo rmmod $1 2> /dev/null"
runcmd "make clean"
runcmd "sudo dmesg -c > /dev/null"
runcmd "make || exit 1"
runcmd "sudo insmod ./$1.ko && lsmod|grep $1"
runcmd dmesg
