#!/bin/bash
# silly kernel module dev helper wrapper script

unset ARCH
unset CROSS_COMPILE

name=$(basename $0)
[ `id -u` -ne 0 ] && {
 echo "$name: Need to be root!"
 exit 1
}

SEP="-----------------------------------------------------------------------"
if [ $# -ne 1 ]; then
	echo "Usage: $name name-of-kernel-module (without the .c)"
	exit 1
fi

echo $SEP
echo "Version info:"
cat /etc/issue
uname -r

echo $SEP
echo "rmmod $1 2> /dev/null"
rmmod $1 2> /dev/null

echo $SEP
echo "make clean"
echo $SEP
make clean

echo $SEP
echo "dmesg -c > /dev/null"
echo $SEP
dmesg -c > /dev/null

echo $SEP
echo "make || exit 1"
echo $SEP
make || exit 1

echo $SEP
echo "insmod ./$1.ko && lsmod|grep $1"
echo $SEP
insmod ./$1.ko && lsmod|grep $1

echo $SEP
echo "dmesg"
echo $SEP
dmesg

