#!/bin/bash
# lshosts.sh
# 
# Quick Description:
# List all hosts on a given subnet.
# Wrapper around nmap..
# 
# Last Updated :
# Created      : 30June2017
# 
# Author:
# Kaiwan N Billimoria
# kaiwan -at- kaiwantech -dot- com
# kaiwanTECH
# 
# License:
# MIT License.
# 
name=$(basename $0)
#source ./common.sh || {
# echo "${name}: fatal: could not source common.sh , aborting..."
# exit 1
#}
SUBNET='192.168.0.*'
 
if [ $# -eq 1 ] ; then
  SUBNET="$1"
elif [ "$1" = "--help" ] ; then
  echo "Usage: ${name} subnet
Eg. ${name} 192.168.1.*"
  exit 1
fi

echo "${name}: scanning subnet ${SUBNET} now, patience pl..."
nmap -sn ${SUBNET}
[ $(id -u) -ne 0 ] && echo "${name}: Tip: run as root for more detail."
exit 0
