#!/bin/bash
# Script to replace the existing Makefile with the 'new & better' "Better
# Makefile" !
# Run it from the folder where the older Makefile exists.
# (c) kaiwanTECH
name=$(basename $0)

die()
{
echo >&2 "FATAL: $*" ; exit 1
}
warn()
{
echo >&2 "WARNING: $*"
}

BETTER_MK=~/Makefile.better.app

#--- 'main'

# validity checks
[[ ! -f Makefile ]] && warn "${name}: no Makefile present?"
numC=$(ls *.c|wc -w)
[[ ${numC} -gt 1 ]] && die  "This Makefile works with only one C source file"
[[ ${numC} -le 0 ]] && die  "No C source files?"
[[ ! -f ${BETTER_MK} ]] && die "${name}: better Makefile not present? aborting..."

[[ -f Makefile ]] && mv Makefile Makefile.old
cp -f ${BETTER_MK} Makefile || die "cp new Makefile failed"

fname_c1=$(ls *.c)
fname_c=${fname_c1::-2}  # get rid of the .c

sed -i "s/^FNAME_C :=.*$/FNAME_C := ${fname_c}/" Makefile
[[ $? -ne 0 ]] && {
	echo "${name}: sed: find/replace failed: $?"
	exit 1
}
grep "^FNAME_C " Makefile || die "${name}: no FNAME_C in Makefile?" && {
  [[ -f Makefile ]] && rm -f  Makefile.old
}
exit 0
